/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rithvik
 */
public class EnterpriseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EnterpriseJFrame
     */
    public EnterpriseJFrame() {
        initComponents();
    }
     Connection con1;
    PreparedStatement insert;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtResidentId = new javax.swing.JTextField();
        txtComplaintId = new javax.swing.JTextField();
        txtComplaintType = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComplaintBox = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtID7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnMale1 = new javax.swing.JRadioButton();
        btnFemale1 = new javax.swing.JRadioButton();
        btnOther1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        btnUpdateMyProfile = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtID3 = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(77, 126, 126));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 650, 130, 50));

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Resident ID", "Complaint ID", "Complaint Type", "Status", "Complaint", "Comment By Worker"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 911, 122));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Resident ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 269, 180, 30));

        btnView.setBackground(new java.awt.Color(77, 126, 126));
        btnView.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, 40));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Complaint ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 371, 180, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Complaint Type :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 422, 180, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Status :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 473, 180, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Complaint Box :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 180, 30));

        txtResidentId.setBackground(new java.awt.Color(204, 204, 204));
        txtResidentId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtResidentId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(txtResidentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, 30));

        txtComplaintId.setBackground(new java.awt.Color(204, 204, 204));
        txtComplaintId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtComplaintId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(txtComplaintId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 160, 30));

        txtComplaintType.setBackground(new java.awt.Color(204, 204, 204));
        txtComplaintType.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtComplaintType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(txtComplaintType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 160, 30));

        txtStatus.setBackground(new java.awt.Color(204, 204, 204));
        txtStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 160, 30));

        txtComplaintBox.setBackground(new java.awt.Color(204, 204, 204));
        txtComplaintBox.setColumns(10);
        txtComplaintBox.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtComplaintBox.setRows(3);
        txtComplaintBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane2.setViewportView(txtComplaintBox);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 250, 100));

        btnSend.setBackground(new java.awt.Color(77, 126, 126));
        btnSend.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSend.setText("Send To Organization");
        btnSend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 250, 50));

        btnCancel.setBackground(new java.awt.Color(77, 126, 126));
        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCancel.setText("Cancel Complaint");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 210, 60));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Comment By Worker :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 210, 30));

        txtComment.setBackground(new java.awt.Color(204, 204, 204));
        txtComment.setColumns(10);
        txtComment.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtComment.setRows(3);
        txtComment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane3.setViewportView(txtComment);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 250, 100));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Complaints :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 23, -1, 30));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Staff ID :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 11, 110, 30));

        txtID7.setBackground(new java.awt.Color(204, 204, 204));
        txtID7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtID7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        txtID7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1151, 12, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Staff1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1280, 750));

        jTabbedPane1.addTab("Enterprise Admin", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Name :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 143, 180, 27));

        txtName1.setBackground(new java.awt.Color(204, 204, 204));
        txtName1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 142, 148, -1));

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Age :");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 206, 180, 27));

        txtAge1.setBackground(new java.awt.Color(204, 204, 204));
        txtAge1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtAge1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        txtAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 206, 148, -1));

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Gender :");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 281, 180, 27));

        genderGroup.add(btnMale1);
        btnMale1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnMale1.setText("Male");
        jPanel2.add(btnMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 281, -1, -1));

        genderGroup.add(btnFemale1);
        btnFemale1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnFemale1.setText("Female");
        jPanel2.add(btnFemale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 281, -1, -1));

        genderGroup.add(btnOther1);
        btnOther1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnOther1.setText("Other");
        jPanel2.add(btnOther1, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 281, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Email :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 354, 180, 27));

        txtEmail1.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 354, 148, -1));

        btnUpdateMyProfile.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateMyProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdateMyProfile.setText("Update");
        btnUpdateMyProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnUpdateMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMyProfileActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdateMyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 115, 51));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Staff ID :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 19, 110, 30));

        txtID3.setBackground(new java.awt.Color(204, 204, 204));
        txtID3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtID3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        txtID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1129, 20, 100, -1));

        btnBack1.setBackground(new java.awt.Color(77, 126, 126));
        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1081, 628, 130, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Staff1.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1280, 750));

        jTabbedPane1.addTab("Update my profile", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainJFrame mf = new MainJFrame();
        mf.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    
    
    public void table_update_griv()
        {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("select * from raisecomplaint where enterprice='Grievance'");
            
             ResultSet rs= insert.executeQuery();
             ResultSetMetaData Rss = rs.getMetaData();
             c = Rss.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            
             Df.setRowCount(0);
             
             while(rs.next())
             {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                 v2.add(rs.getString("id"));
                  v2.add(rs.getString("complaintid"));
                   v2.add(rs.getString("organization"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("complaint"));
                    v2.add(rs.getString("workercomment"));
                 
               
               }
               Df.addRow(v2);
             }
           
                     
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        
        }
          
          
          
          
          
        public void table_update_emergency()
        {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("select * from raisecomplaint where enterprice='emergency'");
            
             ResultSet rs= insert.executeQuery();
             ResultSetMetaData Rss = rs.getMetaData();
             c = Rss.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            
             Df.setRowCount(0);
             
             while(rs.next())
             {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                 v2.add(rs.getString("id"));
                  v2.add(rs.getString("complaintid"));
                   v2.add(rs.getString("organization"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("complaint"));
                    v2.add(rs.getString("workercomment"));
                 
               
               }
               Df.addRow(v2);
             }
           
                     
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        
        }
        
        public void table_update_covidhelp()
        {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("select * from raisecomplaint where enterprice='Covid-Help'");
            
             ResultSet rs= insert.executeQuery();
             ResultSetMetaData Rss = rs.getMetaData();
             c = Rss.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            
             Df.setRowCount(0);
             
             while(rs.next())
             {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                 v2.add(rs.getString("id"));
                  v2.add(rs.getString("complaintid"));
                   v2.add(rs.getString("organization"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("complaint"));
                    v2.add(rs.getString("workercomment"));
                 
               
               }
               Df.addRow(v2);
             }
           
                     
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        
        }
        
         public void table_update_residence()
        {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("select * from raisecomplaint where enterprice='Residence'");
            
             ResultSet rs= insert.executeQuery();
             ResultSetMetaData Rss = rs.getMetaData();
             c = Rss.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            
             Df.setRowCount(0);
             
             while(rs.next())
             {
               Vector v2 = new Vector();
               
               for(int a=1; a<=c; a++)
               {
                 v2.add(rs.getString("id"));
                  v2.add(rs.getString("complaintid"));
                   v2.add(rs.getString("organization"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("complaint"));
                    v2.add(rs.getString("workercomment"));
                 
               
               }
               Df.addRow(v2);
             }
           
                     
           
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(SystemAdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        
        }
    
    
    private void txtAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1ActionPerformed

    private void txtID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID3ActionPerformed

    private void txtID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID7ActionPerformed

    private void btnUpdateMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMyProfileActionPerformed
        // TODO add your handling code here:
        try {
               
              int employeeid=Integer.parseInt(txtID3.getText());
              String name= txtName1.getText();
              int age=Integer.parseInt(txtAge1.getText());
              String email=txtEmail1.getText();
             
        this.btnMale1.setActionCommand("Male");
        this.btnFemale1.setActionCommand("Female");
        this.btnOther1.setActionCommand("Other");
              String selection = this.genderGroup.getSelection().getActionCommand();
              
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("update employeeregistration set name=?, age=?, gender=?, email=? where employeeid=?");
            
            insert.setString(1, name);
            insert.setInt(2, age);
            insert.setString(3, selection);
            insert.setString(4,email);
            insert.setInt(5, employeeid);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"My Profile Updated");
                  
            txtName1.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResidentComplaintJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(ResidentComplaintJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateMyProfileActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
         int selectedIndex =  jTable1.getSelectedRow();
         
         
         txtResidentId.setText(Df.getValueAt(selectedIndex,0).toString());
         txtComplaintId.setText(Df.getValueAt(selectedIndex,1).toString());
         txtComplaintType.setText(Df.getValueAt(selectedIndex,2).toString());
         txtStatus.setText(Df.getValueAt(selectedIndex,3).toString());
         txtComplaintBox.setText(Df.getValueAt(selectedIndex,4).toString());
         txtComment.setText(Df.getValueAt(selectedIndex,5).toString());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
//         int selectedIndex = jTable1.getSelectedRow();
//          try {
//              
//              
//              int id=Integer.parseInt(Df.getValueAt(selectedIndex, 1).toString());
//              
//              int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
//              if(dialogResult==JOptionPane.YES_OPTION)
//              {
//                  Class.forName("com.mysql.jdbc.Driver");
//            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
//            insert=con1.prepareStatement("delete from raisecomplaint where complaintid=?");
//            
//             insert.setInt(1, id);
//            insert.executeUpdate();
//            
//            JOptionPane.showMessageDialog(this,"Record Delete");
//            
//              table_update_griv();
//              table_update_emergency();
//              table_update_covidhelp();
//              table_update_residence();
//            
//              }
//          
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(ResidentComplaintJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        catch (SQLException ex) {
//            Logger.getLogger(ResidentComplaintJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }

DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
         int selectedIndex = jTable1.getSelectedRow();
         
          try {
              
              
              int complaintid=Integer.parseInt(Df.getValueAt(selectedIndex, 1).toString());
              int residentid=Integer.parseInt(txtResidentId.getText());
              
              String complainttype=txtComplaintType.getText();
              String status=txtStatus.getText();
              String comment=txtComment.getText();
              String complaintbox=txtComplaintBox.getText();
              
              
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("update raisecomplaint set id=?,organization=?,complaint=?, status='cancelled',workercomment=? where complaintid=?");
            
            insert.setInt(1, residentid);
            insert.setString(2, complainttype);
            insert.setString(3, complaintbox);
            //insert.setString(4, status);
            insert.setString(4, comment);
            insert.setInt(5, complaintid);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Updated");
             
             ManagerJFrame m = new ManagerJFrame();
             m.table_update_water();
             m.table_update_fire();
             m.table_update_gov();
             m.table_update_hospital();
             m.table_update_nongov();
             m.table_update_police();
             m.table_update_standalone();
             m.table_update_street();
             
             
              table_update_griv();
              table_update_emergency();
              table_update_covidhelp();
              table_update_residence();
            
          
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EnterpriseJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(EnterpriseJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
         int selectedIndex = jTable1.getSelectedRow();
         
          try {
              
              
              int complaintid=Integer.parseInt(Df.getValueAt(selectedIndex, 1).toString());
              int residentid=Integer.parseInt(txtResidentId.getText());
              
              String complainttype=txtComplaintType.getText();
              String status=txtStatus.getText();
              String comment=txtComment.getText();
              String complaintbox=txtComplaintBox.getText();
              
              
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/bostonsmartcity","root","root@123");
            insert=con1.prepareStatement("update raisecomplaint set id=?,organization=?,complaint=?, status='pending',workercomment=? where complaintid=?");
            
            insert.setInt(1, residentid);
            insert.setString(2, complainttype);
            insert.setString(3, complaintbox);
            //insert.setString(4, status);
            insert.setString(4, comment);
            insert.setInt(5, complaintid);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Updated");
             
             ManagerJFrame m = new ManagerJFrame();
             m.table_update_water();
             m.table_update_fire();
             m.table_update_gov();
             m.table_update_hospital();
             m.table_update_nongov();
             m.table_update_police();
             m.table_update_standalone();
             m.table_update_street();
             
             
              table_update_griv();
              table_update_emergency();
              table_update_covidhelp();
              table_update_residence();
            
          
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EnterpriseJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (SQLException ex) {
            Logger.getLogger(EnterpriseJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterpriseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterpriseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterpriseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterpriseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterpriseJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCancel;
    public javax.swing.JRadioButton btnFemale1;
    public javax.swing.JRadioButton btnMale1;
    public javax.swing.JRadioButton btnOther1;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnUpdateMyProfile;
    private javax.swing.JButton btnView;
    public javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txtAge1;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextArea txtComplaintBox;
    private javax.swing.JTextField txtComplaintId;
    private javax.swing.JTextField txtComplaintType;
    public javax.swing.JTextField txtEmail1;
    public javax.swing.JTextField txtID3;
    public javax.swing.JTextField txtID7;
    public javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtResidentId;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
